### ISSUE TITLE
Can't start eth1indexer

### ISSUE THREAD

**Issue by eliotstock** [gobitfly/eth-explorer-workshop-bogota#1]
Following the `run.sh` commands in your PDF slides, I get this at the second step:

```
$./run.sh start-eth1indexer
[+] Running 6/6
 ⠿ eth1indexer Pulled                                                                                            9.0s
   ⠿ 6e3729cf69e0 Already exists                                                                                 0.0s
   ⠿ 5f0d73cb3b8d Pull complete                                                                                  1.4s
   ⠿ 8741a89d352d Pull complete                                                                                  1.4s
   ⠿ f2a49308e663 Pull complete                                                                                  5.7s
   ⠿ a2e45447b0ae Pull complete                                                                                  5.7s
[+] Running 1/2
 ⠿ Container eth-explorer-workshop-bogota-bigtable-1     Running                                                 0.0s
 ⠿ Container eth-explorer-workshop-bogota-eth1indexer-1  Starting                                                0.5s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "eth1indexer": executable file not found in $PATH: unknown

```

**Comment by cppfuns** [comment]
I also encountered the same problem 
I need to solve this problem urgently, I have been stuck for a long time, please help me to solve it
@Buttaa @guybrush @qu0b @recy21

**Comment by recy21** [comment]
Hey, the problem seems to be a missing path, so changing (in [docker-compose.yml](https://github.com/gobitfly/eth-explorer-workshop-bogota/blob/master/docker-compose.yml))...
```
    ...
    command: 
      - eth1indexer
    ...
```
...to...
```
    ...
    command: 
      - ./eth1indexer
    ...
```
... will fix the problem. For the other services the same problem might occur, with the same fix to go.

But as the Explorer itself is currently under high development, there is simply no time for updating all related repositories and/or keeping the documentation up to date. So, pretty sure, there will be other issues as well.
We will try our best to catch up after the explorer has all its new features ready, but I would suggest to use an older version of the explorer meanwhile.

**Comment by recy21** [comment]
Closing this as resolved, please create another issue if necessary.
